export const BannerData = [
  {
    id: "1",
    title: "UPGRADE YOUR",
    subTitle: "FITNESS JOURNEY",
    desc: "Explore our range of advanced treadmills for a high-performance cardio experience.",
    descClr: "#ffffff",
    img: "/banner-1.jpg",
    link: "/categories/Treadmills",
    btnText: "Shop Treadmills",
  },
  {
    id: "2",
    title: "TRAIN SMARTER",
    subTitle: "LIFT HEAVIER",
    desc: "Discover premium weightlifting equipment and elevate your strength training.",
    descClr: "#ffffff",
    img: "/banner-2.jpg",
    link: "/categories/Weightlifting",
    btnText: "Shop Weights",
  },
  {
    id: "3",
    title: "STAY FLEXIBLE",
    subTitle: "AND STRONG",
    desc: "Browse yoga mats, resistance bands, and tools for the perfect stretching routine.",
    descClr: "#ffffff",
    img: "/banner-3.jpg",
    link: "/categories/Yoga",
    btnText: "Shop Yoga Gear",
  },
  {
    id: "4",
    title: "COMPACT",
    subTitle: "HOME GYMS",
    desc: "Build your ultimate home gym with our multi-functional compact equipment.",
    descClr: "#ffffff",
    img: "/banner-4.jpg",
    link: "/categories/HomeGyms",
    btnText: "Shop Home Gyms",
  },
  {
    id: "5",
    title: "RECOVER BETTER",
    subTitle: "PERFORM STRONGER",
    desc: "Optimize recovery with massage guns, foam rollers, and therapy tools.",
    descClr: "#ffffff",
    img: "/banner-5.jpg",
    link: "/categories/Recovery",
    btnText: "Shop Recovery Tools",
  },
  {
    id: "6",
    title: "CRUSH YOUR",
    subTitle: "CARDIO GOALS",
    desc: "High-performance exercise bikes for your endurance and fitness training.",
    descClr: "#ffffff",
    img: "/banner-6.jpg",
    link: "/categories/ExerciseBikes",
    btnText: "Shop Exercise Bikes",
  },
  {
    id: "7",
    title: "ON-THE-GO",
    subTitle: "WORKOUT ESSENTIALS",
    desc: "Portable fitness accessories for wherever your workouts take you.",
    descClr: "#ffffff",
    img: "/banner-7.jpg",
    link: "/categories/Accessories",
    btnText: "Shop Accessories",
  },
  {
    id: "8",
    title: "YOUR FITNESS,",
    subTitle: "YOUR WAY",
    desc: "Flexible financing options for all gym equipment purchases.",
    descClr: "#ffffff",
    img: "/banner-8.1.jpg",
    link: "/financing",
    btnText: "Learn More",
  },
];
