import { Icon } from "@iconify/react";

export const BannerData = [
  {
    id: "1",
    title: "UPGRADE YOUR",
    subTitle: "FITNESS JOURNEY",
    desc: "Explore our range of advanced treadmills for a high-performance cardio experience.",
    descClr: "#ffffff",
    img: "/banner-1.jpg",
    link: "/categories/Treadmills",
    btnText: "Shop Treadmills",
  },
  {
    id: "2",
    title: "TRAIN SMARTER",
    subTitle: "LIFT HEAVIER",
    desc: "Discover premium weightlifting equipment and elevate your strength training.",
    descClr: "#ffffff",
    img: "/banner-2.jpg",
    link: "/categories/Weightlifting",
    btnText: "Shop Weights",
  },
  {
    id: "3",
    title: "STAY FLEXIBLE",
    subTitle: "AND STRONG",
    desc: "Browse yoga mats, resistance bands, and tools for the perfect stretching routine.",
    descClr: "#ffffff",
    img: "/banner-3.jpg",
    link: "/categories/Yoga",
    btnText: "Shop Yoga Gear",
  },
  {
    id: "4",
    title: "COMPACT",
    subTitle: "HOME GYMS",
    desc: "Build your ultimate home gym with our multi-functional compact equipment.",
    descClr: "#ffffff",
    img: "/banner-4.jpg",
    link: "/categories/HomeGyms",
    btnText: "Shop Home Gyms",
  },
  {
    id: "5",
    title: "RECOVER BETTER",
    subTitle: "PERFORM STRONGER",
    desc: "Optimize recovery with massage guns, foam rollers, and therapy tools.",
    descClr: "#ffffff",
    img: "/banner-5.jpg",
    link: "/categories/Recovery",
    btnText: "Shop Recovery Tools",
  },
  {
    id: "6",
    title: "CRUSH YOUR",
    subTitle: "CARDIO GOALS",
    desc: "High-performance exercise bikes for your endurance and fitness training.",
    descClr: "#ffffff",
    img: "/banner-6.jpg",
    link: "/categories/ExerciseBikes",
    btnText: "Shop Exercise Bikes",
  },
  {
    id: "7",
    title: "ON-THE-GO",
    subTitle: "WORKOUT ESSENTIALS",
    desc: "Portable fitness accessories for wherever your workouts take you.",
    descClr: "#ffffff",
    img: "/banner-7.jpg",
    link: "/categories/Accessories",
    btnText: "Shop Accessories",
  },
  {
    id: "8",
    title: "YOUR FITNESS,",
    subTitle: "YOUR WAY",
    desc: "Flexible financing options for all gym equipment purchases.",
    descClr: "#ffffff",
    img: "/banner-8.jpg",
    link: "/financing",
    btnText: "Learn More",
  },
];

export const CategoryData = [
  {
    id: 1,
    name: "Treadmills",
    icon: <Icon icon="mdi:run" />,
    link: "/categories/Treadmills",
  },
  {
    id: 2,
    name: "Exercise Bikes",
    icon: <Icon icon="mdi:bike" />,
    link: "/categories/ExerciseBikes",
  },
  {
    id: 3,
    name: "Dumbbells & Weights",
    icon: <Icon icon="mdi:dumbbell" />,
    link: "/categories/DumbbellsAndWeights",
  },
  {
    id: 4,
    name: "Yoga & Pilates",
    icon: <Icon icon="mdi:yoga" />,
    link: "/categories/YogaAndPilates",
  },
  {
    id: 5,
    name: "Resistance Bands",
    icon: <Icon icon="mdi:bandage" />,
    link: "/categories/ResistanceBands",
  },
  {
    id: 6,
    name: "Home Gyms",
    icon: <Icon icon="mdi:home-circle-outline" />,
    link: "/categories/HomeGyms",
  },
  {
    id: 7,
    name: "Boxing & Martial Arts",
    icon: <Icon icon="mdi:boxing-glove" />,
    link: "/categories/BoxingAndMartialArts",
  },
  {
    id: 8,
    name: "Recovery Equipment",
    icon: <Icon icon="mdi:massage" />,
    link: "/categories/RecoveryEquipment",
  },
  {
    id: 9,
    name: "Jump Ropes",
    icon: <Icon icon="mdi:rope" />,
    link: "/categories/JumpRopes",
  },
  {
    id: 10,
    name: "Gym Accessories",
    icon: <Icon icon="mdi:fitness-center" />,
    link: "/categories/GymAccessories",
  },
  {
    id: 11,
    name: "Foam Rollers",
    icon: <Icon icon="mdi:roller" />,
    link: "/categories/FoamRollers",
  },
  {
    id: 12,
    name: "Kettlebells",
    icon: <Icon icon="mdi:kettlebell" />,
    link: "/categories/Kettlebells",
  },
  {
    id: 13,
    name: "Sports Apparel",
    icon: <Icon icon="mdi:tshirt-crew-outline" />,
    link: "/categories/SportsApparel",
  },
  {
    id: 14,
    name: "Gloves & Straps",
    icon: <Icon icon="mdi:handshake-outline" />,
    link: "/categories/GlovesAndStraps",
  },
  {
    id: 15,
    name: "Water Bottles",
    icon: <Icon icon="mdi:bottle-soda-outline" />,
    link: "/categories/WaterBottles",
  },
];
